### ISSUE TITLE
Interact Home Computer BIOS

### ISSUE THREAD

**Issue by ajgowans** [theypsilon/MiSTer_BIOS_SCRIPTS#18]
The Interact Home Computer needs a BIOS file:

"Rename the Interact ROM file to boot.rom and place in games/Interact"

https://github.com/MiSTer-devel/Interact_MiSTer

**Comment by theypsilon** [comment]
Fixed, thanks for reporting it!

**Comment by theypsilon** [comment]
https://github.com/theypsilon/MiSTer_BIOS_SCRIPTS/commit/727ff57ae6708895d74fe947880b686086d8f33f
