### ISSUE TITLE
BIOS updater script does not copy all NeoGeo ROM files into correct final locations

### ISSUE THREAD

**Issue by c0d3h4x0r** [theypsilon/MiSTer_BIOS_SCRIPTS#20]
The BIOS updater script neglects to perform the following copy operations after downloading the files:

- `/media/fat/BIOS/NeoGeo/neo-epo.sp1-AES_BIOS` >> `/media/fat/games/NeoGeo/neo-epo.sp1`
- `/media/fat/BIOS/NeoGeo/sp-s2.sp1-MVS_BIOS` >> `/media/fat/games/NeoGeo/sp-s2.sp1`

**Comment by theypsilon** [comment]
Sounds like a good suggestion, now that selecting between bios is possible in the core. I'll do some tests. Thanks for opening the issue!

**Comment by c0d3h4x0r** [comment]
Aren't those ROM files needed by UniBIOS regardless?

Sent via Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by theypsilon** [comment]
They weren't needed. I've just implemented your suggestion and now it copies all 5 bioses. Thanks again!
