### ISSUE TITLE
Request: Add scph1001.bin --> boot.rom in Playstation folder

### ISSUE THREAD

**Issue by birdybro** [theypsilon/MiSTer_BIOS_SCRIPTS#21]
Please add scph1001.bin to the list and rename to boot.rom and place in the /games/Playstation folder (and create folder if it's not there).

name: ps-10j.bin (or scph1001.bin commonly)
md5: 239665B1A3DADE1B5A52C06338011044

Now that regular playstation core is being added to Downloader as an unstable core option, this will help reduce the number of people needing help with this core folder creation (case-sensitivity for instance) and bios.

**Comment by theypsilon** [comment]
This was already added
