### ISSUE TITLE
Request: Gamate BIOS

### ISSUE THREAD

**Issue by ajgowans** [theypsilon/MiSTer_BIOS_SCRIPTS#24]
Hey there, we now have a Gamate core which requires a BIOS file.  There are two out there, this is the later revision so probably the one to go for:
gamate_bios_umc.bin

Note: it would be worth prepping for a GameKing BIOS to be added as well in the coming weeks, this one can be harder to find, if you are struggling ping moondandy on discord ;-)

**Comment by theypsilon** [comment]
Added, thank you!
